In [1]:
# imports :
import pandas as pd
import re
import nltk

In [2]:
# télécharger ressources :
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\berna\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\berna\AppData\Roaming\nltk_data...

True

In [3]:
# charger dataset :
dataset = pd.read_csv("../data/dataset_final.csv")

dataset.head()

                                                text label
0  Message-ID: <18782981.1075855378110.JavaMail.e...   ham
1  Message-ID: <15464986.1075855378456.JavaMail.e...   ham
2  Message-ID: <24216240.1075855687451.JavaMail.e...   ham
3  Message-ID: <13505866.1075863688222.JavaMail.e...   ham
4  Message-ID: <30922949.1075863688243.JavaMail.e...   ham

In [4]:
# outils nlp :
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))

lemmatizer = WordNetLemmatizer()

In [5]:
# Fonction de nettoyage :
def clean_text(text):
    
    text = text.lower()
    
    # supprimer HTML
    text = re.sub(r"<.*?>", " ", text)
    
    # supprimer URLs
    text = re.sub(r"http\S+|www\S+", " ", text)
    
    # supprimer emails
    text = re.sub(r"\S+@\S+", " ", text)
    
    # supprimer chiffres
    text = re.sub(r"\d+", " ", text)
    
    # supprimer ponctuation
    text = re.sub(r"[^\w\s]", " ", text)
    
    # supprimer espaces multiples
    text = re.sub(r"\s+", " ", text).strip()
    
    # tokenisation
    words = text.split()
    
    # stopwords + lemmatisation
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]
    
    return " ".join(words)

In [6]:
# test rapide :
sample = dataset["text"].iloc[0]

print("AVANT :")
print(sample)

print("\nAPRÈS :")
print(clean_text(sample))

AVANT :
Message-ID: <18782981.1075855378110.JavaMail.evans@thyme>
Date: Mon, 14 May 2001 16:39:00 -0700 (PDT)
From: phillip.allen@enron.com
To: tim.belden@enron.com
Subject:
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
X-From: Phillip K Allen
X-To: Tim Belden <Tim Belden/Enron@EnronXGate>
X-cc:
X-bcc:
X-Folder: \Phillip_Allen_Jan2002_1\Allen, Phillip K.\'Sent Mail
X-Origin: Allen-P
X-FileName: pallen (Non-Privileged).pst

Here is our forecast



APRÈS :
message id date mon may pdt subject mime version content type text plain charset u ascii content transfer encoding bit x phillip k allen x tim belden x cc x bcc x folder phillip_allen_jan _ allen phillip k sent mail x origin allen p x filename pallen non privileged pst forecast

In [7]:
# appliquer tout sur le dataset :
dataset["clean_text"] = dataset["text"].apply(clean_text)

In [8]:
# vérification :
dataset[["text","clean_text"]].sample(5)

,text,clean_text
106984,"2008/3/25, Alex Martelli :\n\n> > Since we ha...",alex martelli since strong use case least byte...
3991,Message-ID: <24131626.1075857571115.JavaMail.e...,message id date fri dec pst subject big news c...
20175,Message-ID: <3253820.1075855145890.JavaMail.ev...,message id date thu sep pdt subject forwarding...
123465,\n\nAstrology.com Daily Work Horoscope\n\n\n\n...,astrology com daily work horoscope dear gordon...
212612,barnett scott barnett_scottweb2mailcom barrist...,barnett scott barnett_scottweb mailcom barrist...

In [9]:
# save :
dataset.to_csv("../data/dataset_clean.csv", index=False)